[project]
name = "automl"
version = "0.1.0"
description = "automated machine learning framework"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "scikit-learn>=1.7.1",
    "setuptools>=80.9.0",
    "wxpython>=4.2.3",
]
