[project]
name = "automl"
version = "0.1.0"
description = "automated machine learning framework"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.1",
    "wxpython>=4.2.3",
]
